# Generated by Django 4.0.6 on 2022-07-21 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alignmentmodel_alignmentmodeloutput_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlignmentModelOutputSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats', models.JSONField(verbose_name='Statistics, Evaluation Metrics: Precision, Recall, F1, and AER at sentence level')),
                ('sentence_id', models.CharField(max_length=10, verbose_name='Sentence ID')),
                ('alignments', models.JSONField(verbose_name='Sure Alignments')),
            ],
        ),
        migrations.AlterField(
            model_name='alignmentmodel',
            name='title',
            field=models.JSONField(help_text='Unique Name to be used in the frontend. eg.: SimAlign-, En-Fr, ..etc', unique=True, verbose_name='Alignment Model'),
        ),
        migrations.AlterField(
            model_name='gssentence',
            name='sentence_id',
            field=models.CharField(help_text='A unique ID within the data set.', max_length=10, verbose_name='Sentence ID'),
        ),
        migrations.AlterUniqueTogether(
            name='alignmentmodeloutput',
            unique_together={('model', 'dataset')},
        ),
        migrations.DeleteModel(
            name='AlignmentModelOutputSentences',
        ),
        migrations.AddField(
            model_name='alignmentmodeloutputsentence',
            name='modelOutput',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alignmentmodeloutput'),
        ),
        migrations.AlterUniqueTogether(
            name='alignmentmodeloutputsentence',
            unique_together={('modelOutput_id', 'sentence_id')},
        ),
    ]
