# Generated by Django 4.0.6 on 2022-07-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alignmentmodeloutputsentence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alignmentmodeloutputsentence',
            name='pairs',
            field=models.JSONField(default=[], verbose_name='Translation pairs.'),
        ),
        migrations.AlterField(
            model_name='alignmentmodeloutputsentence',
            name='alignments',
            field=models.JSONField(verbose_name='Model prediction.'),
        ),
    ]
