# Generated by Django 4.0.6 on 2022-07-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alignmentmodeloutputsentence_pairs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alignmentmodeloutputsentence',
            name='pairs',
            field=models.JSONField(default={}, verbose_name='Translation pairs.'),
        ),
    ]
