# Generated by Django 4.0.6 on 2022-07-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_alignmentmodeloutputsentence_pairs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alignmentmodel',
            name='title',
            field=models.CharField(default='', help_text='Unique Name to be used in the frontend. eg.: SimAlign-, En-Fr, ..etc', max_length=100, unique=True, verbose_name='Alignment Model'),
        ),
        migrations.AlterField(
            model_name='gsdataset',
            name='title',
            field=models.CharField(default='', help_text='Unique Name to be used in the frontend. eg.: De-En, En-Fr, ..etc', max_length=100, verbose_name='Data set name'),
        ),
    ]
